version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todo_app}
      MYSQL_USER: ${MYSQL_USER:-todouser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-todopass}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-h127.0.0.1", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  db-data: